version: "3"
dotenv: ['.env']
tasks:
    build:
        cmds:
            - go build -o bin/tg-bot ./cmd/main.go
        env:
            GOOS: linux
            GOARCH: amd64
    deploy:
        cmds:
            - task: build
            - ssh root@$REMOTE_HOST "cp /home/bot/tg-bot /home/bot/tg-bot.bak"
            - rsync -avz  bin/tg-bot root@$REMOTE_HOST:/home/bot
            - ssh root@$REMOTE_HOST "sudo supervisorctl restart mytgbot"
    rollback:
        cmds:
            - ssh root@$REMOTE_HOST "cp -f /home/bot/tg-bot.bak /home/bot/tg-bot"
            - ssh root@$REMOTE_HOST "sudo supervisorctl restart mytgbot"