version: "3"
dotenv: ['.env']
tasks:
    build:
        cmds:
            - go build -o bin/tg-bot ./cmd/main.go
        env:
            GOOS: linux
            GOARCH: amd64
    deploy:
        cmds:
            - task: build
            - rsync -avz  bin/tg-bot root@$REMOTE_HOST:/home/bot
            - ssh root@$REMOTE_HOST "sudo supervisorctl restart mytgbot"