models:
  - name: GPT-4o
    model_id: gpt-4o
    provider: openai
  - name: GPT-4o-mini
    model_id: gpt-4o-mini
    provider: openai
  - name: GPT-4 Turbo
    model_id: gpt-4-turbo-2024-04-09
    provider: openai
  - name: Claude 3.5 Sonnet
    model_id: claude-3-5-sonnet-latest
    provider: anthropic
