dialog_timeout: 1800
max_concurrent_requests: 1
default_model:
  model_id: gpt-4o-2024-08-06
models:
  - name: GPT-4o
    model_id: gpt-4o-2024-08-06
    provider: openai
  - name: GPT-4o-mini
    model_id: gpt-4o-mini-2024-07-18
    provider: openai
  - name: GPT-o1
    model_id: o1-2024-12-17
    provider: openai
  - name: GPT-o3 mini
    model_id: o3-mini-2025-01-31
    provider: openai
  - name: Claude 3.5 Sonnet
    model_id: claude-3-5-sonnet-latest
    provider: anthropic
